// <auto-generated />
using System;
using DATA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DATA.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20230430235216_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("DATA.Model.ApplicationForm", b =>
                {
                    b.Property<int>("ApplicationFormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AboutYourself")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentRecidence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumberId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Resume")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadImage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ApplicationFormId");

                    b.ToTable("ApplicationForms");
                });

            modelBuilder.Entity("DATA.Model.ProgramDetails", b =>
                {
                    b.Property<int>("ProgramDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ApplicationClose")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplicationCriteria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ApplicationOpen")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<string>("KeySlides")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxApplications")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MinQualification")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProgramBenefits")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProgramLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ProgramStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProgramType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProgramDetailsId");

                    b.ToTable("ProgramDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
